# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChooseShow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43hooseShow.proto\x12\nChooseShow\")\n\x11\x43hooseShowRequest\x12\x14\n\x0cshow_slot_id\x18\x01 \x01(\x0c\"o\n\x12\x43hooseShowResponse\x12\x36\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32(.ChooseShow.ChooseShowResponse.InnerData\x1a!\n\tInnerData\x12\x14\n\x0cshow_slot_id\x18\t \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChooseShow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHOOSESHOWREQUEST._serialized_start=32
  _CHOOSESHOWREQUEST._serialized_end=73
  _CHOOSESHOWRESPONSE._serialized_start=75
  _CHOOSESHOWRESPONSE._serialized_end=186
  _CHOOSESHOWRESPONSE_INNERDATA._serialized_start=153
  _CHOOSESHOWRESPONSE_INNERDATA._serialized_end=186
# @@protoc_insertion_point(module_scope)
