# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChooseSlotsAndShow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hooseSlotsAndShow.proto\"\x86\x01\n\x19\x43hooseSlotsAndShowRequest\x12\x32\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32$.ChooseSlotsAndShowRequest.InnerData\x1a\x35\n\tInnerData\x12\x12\n\nslots_blob\x18\x07 \x01(\x0c\x12\x14\n\x0cshow_slot_id\x18\t \x01(\x0c\"\x88\x01\n\x1a\x43hooseSlotsAndShowResponse\x12\x33\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32%.ChooseSlotsAndShowResponse.InnerData\x1a\x35\n\tInnerData\x12\x12\n\nslots_blob\x18\x07 \x01(\x0c\x12\x14\n\x0cshow_slot_id\x18\t \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChooseSlotsAndShow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHOOSESLOTSANDSHOWREQUEST._serialized_start=29
  _CHOOSESLOTSANDSHOWREQUEST._serialized_end=163
  _CHOOSESLOTSANDSHOWREQUEST_INNERDATA._serialized_start=110
  _CHOOSESLOTSANDSHOWREQUEST_INNERDATA._serialized_end=163
  _CHOOSESLOTSANDSHOWRESPONSE._serialized_start=166
  _CHOOSESLOTSANDSHOWRESPONSE._serialized_end=302
  _CHOOSESLOTSANDSHOWRESPONSE_INNERDATA._serialized_start=110
  _CHOOSESLOTSANDSHOWRESPONSE_INNERDATA._serialized_end=163
# @@protoc_insertion_point(module_scope)
