# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChooseEmote.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43hooseEmote.proto\x12\x04game\"1\n\x10\x43hooseProfileReq\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x0f\n\x07item_id\x18\x02 \x01(\r\"3\n\x10\x43hooseProfileRes\x12\x1f\n\x04info\x18\x01 \x01(\x0b\x32\x11.game.ProfileInfo\"\xe9\x01\n\x0bProfileInfo\x12\x19\n\x11\x62\x61nner_id_primary\x18\x05 \x01(\r\x12\x11\n\tavatar_id\x18\x06 \x01(\r\x12\x10\n\x08raw_blob\x18\x07 \x01(\x0c\x12#\n\x08\x65quipped\x18\x08 \x01(\x0b\x32\x11.game.ProfileList\x12\x0e\n\x06pin_id\x18\x0c \x01(\r\x12&\n\x08patterns\x18\x0e \x03(\x0b\x32\x14.game.ProfilePattern\x12\x1a\n\x12\x62\x61nner_id_override\x18\x0f \x01(\r\x12!\n\x05\x65xtra\x18\x10 \x01(\x0b\x32\x12.game.ProfileExtra\".\n\x0bProfileList\x12\x1f\n\x04slot\x18\x01 \x03(\x0b\x32\x11.game.ProfileSlot\",\n\x0bProfileSlot\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x0f\n\x07item_id\x18\x02 \x01(\x04\":\n\x0eProfilePattern\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04mode\x18\x03 \x01(\r\"0\n\x0cProfileExtra\x12 \n\x06\x62locks\x18\x02 \x03(\x0b\x32\x10.game.ExtraBlock\"6\n\nExtraBlock\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x64\x61ta1\x18\x02 \x01(\x0c\x12\r\n\x05\x64\x61ta2\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChooseEmote_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHOOSEPROFILEREQ._serialized_start=27
  _CHOOSEPROFILEREQ._serialized_end=76
  _CHOOSEPROFILERES._serialized_start=78
  _CHOOSEPROFILERES._serialized_end=129
  _PROFILEINFO._serialized_start=132
  _PROFILEINFO._serialized_end=365
  _PROFILELIST._serialized_start=367
  _PROFILELIST._serialized_end=413
  _PROFILESLOT._serialized_start=415
  _PROFILESLOT._serialized_end=459
  _PROFILEPATTERN._serialized_start=461
  _PROFILEPATTERN._serialized_end=519
  _PROFILEEXTRA._serialized_start=521
  _PROFILEEXTRA._serialized_end=569
  _EXTRABLOCK._serialized_start=571
  _EXTRABLOCK._serialized_end=625
# @@protoc_insertion_point(module_scope)
